[uuid(8E5B35CA-F76A-4689-9547-F28FAA94E686),
 version(1.0),
 endpoint("ncalrpc:[MyRcpServer]")]
interface MyRpc {
    [helpstring("Print a message to the server console")]
    void PrintMessage([in,string] const wchar_t* msg);

    [helpstring("Compute the sum of two integers")]
    int ComputeSum([in] int a, [in] int b);

    [helpstring("Request the server to shut down")]
    void RequestShutdown();
}
